# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AITailor.Wakemark
PackageVersion: 0.7.2
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Wakemark
  Publisher: "AITailor OÜ"
  ProductCode: Wakemark
Installers:
- Architecture: x64
  InstallerUrl: https://wakemark.io/download/0.7.2/wakemark-windows-x64-setup.exe
  InstallerSha256: AE00F7A5E9F64968416AFB71B0905C79BC007A55EE4006F679D28D2E555A90D9
ManifestType: installer
ManifestVersion: 1.12.0
