# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AITailor.Wakemark
PackageVersion: 0.6.1
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- DisplayName: Wakemark
  Publisher: "AITailor OÜ"
  ProductCode: Wakemark
Installers:
- Architecture: x64
  InstallerUrl: https://wakemark.io/download/0.6.1/wakemark-windows-x64-setup.exe
  InstallerSha256: 0CEC54F82ECC409355B52DE1A7BD361FDAC765C6B7B771FC2664D3E102FDE7B6
ManifestType: installer
ManifestVersion: 1.12.0
